version: '3.8'

services:
  web:
    build: .
    command: ["gunicorn", "--workers", "3", "inventory_project.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./inventory_project/.env

volumes:
  static_volume:
  media_volume:
